### ISSUE TITLE
Probably a bug in Ivatar.php@validateExport

### ISSUE THREAD

**Issue by merlivincenzo** [cloudratha/ivatar#2]
Hi, I'm using your laravel library for generating ivatars. If in the config file you set a specific public path (and so if you don't leave empty string in `export` parameter, you will get an error because the library tries to create a directory using the path of `font` parameter instead of `export` parameter.
The error is on line 98 of the file [Ivatar.php](https://github.com/cloudratha/ivatar/blob/master/src/Cuzzy/Ivatar/Ivatar.php), method `validateExport`
The ternary operator on line 98 will assign `font` config path if `export` parameter is not empty and it seems to be wrong.

**Comment by cloudratha** [comment]
Ah yes,

I see the issue. Will do an update when I have a chance.
Thanks.

**Comment by cloudratha** [comment]
#3 Closes
